# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x02\"\x1f\n\rNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x02\"\x1c\n\x0bSumResponse\x12\r\n\x05total\x18\x01 \x01(\x02\"!\n\x0fMultiplyRequest\x12\x0e\n\x06number\x18\x01 \x01(\x02\"6\n\x10MultiplyResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x12\x12\n\nmultiplier\x18\x02 \x01(\x05\"4\n\x10OperationRequest\x12\t\n\x01\x61\x18\x01 \x01(\x02\x12\t\n\x01\x62\x18\x02 \x01(\x02\x12\n\n\x02op\x18\x03 \x01(\t\"8\n\x11OperationResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2\xa4\x02\n\nCalculator\x12\x36\n\x03\x41\x64\x64\x12\x16.calculator.AddRequest\x1a\x17.calculator.AddResponse\x12\x42\n\nRunningSum\x12\x19.calculator.NumberRequest\x1a\x17.calculator.SumResponse(\x01\x12L\n\rMultiplyTable\x12\x1b.calculator.MultiplyRequest\x1a\x1c.calculator.MultiplyResponse0\x01\x12L\n\tCalculate\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=32
  _globals['_ADDREQUEST']._serialized_end=66
  _globals['_ADDRESPONSE']._serialized_start=68
  _globals['_ADDRESPONSE']._serialized_end=97
  _globals['_NUMBERREQUEST']._serialized_start=99
  _globals['_NUMBERREQUEST']._serialized_end=130
  _globals['_SUMRESPONSE']._serialized_start=132
  _globals['_SUMRESPONSE']._serialized_end=160
  _globals['_MULTIPLYREQUEST']._serialized_start=162
  _globals['_MULTIPLYREQUEST']._serialized_end=195
  _globals['_MULTIPLYRESPONSE']._serialized_start=197
  _globals['_MULTIPLYRESPONSE']._serialized_end=251
  _globals['_OPERATIONREQUEST']._serialized_start=253
  _globals['_OPERATIONREQUEST']._serialized_end=305
  _globals['_OPERATIONRESPONSE']._serialized_start=307
  _globals['_OPERATIONRESPONSE']._serialized_end=363
  _globals['_CALCULATOR']._serialized_start=366
  _globals['_CALCULATOR']._serialized_end=658
# @@protoc_insertion_point(module_scope)
