# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculator_pb2 as calculator__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class CalculatorStub(object):
    """Service Definition

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/calculator.Calculator/Add',
                request_serializer=calculator__pb2.AddRequest.SerializeToString,
                response_deserializer=calculator__pb2.AddResponse.FromString,
                _registered_method=True)
        self.RunningSum = channel.stream_unary(
                '/calculator.Calculator/RunningSum',
                request_serializer=calculator__pb2.NumberRequest.SerializeToString,
                response_deserializer=calculator__pb2.SumResponse.FromString,
                _registered_method=True)
        self.MultiplyTable = channel.unary_stream(
                '/calculator.Calculator/MultiplyTable',
                request_serializer=calculator__pb2.MultiplyRequest.SerializeToString,
                response_deserializer=calculator__pb2.MultiplyResponse.FromString,
                _registered_method=True)
        self.Calculate = channel.stream_stream(
                '/calculator.Calculator/Calculate',
                request_serializer=calculator__pb2.OperationRequest.SerializeToString,
                response_deserializer=calculator__pb2.OperationResponse.FromString,
                _registered_method=True)


class CalculatorServicer(object):
    """Service Definition

    """

    def Add(self, request, context):
        """Pattern 1 - Unary: one request → one response (like a normal function call)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunningSum(self, request_iterator, context):
        """Pattern 2 - Client Streaming: many requests → one response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MultiplyTable(self, request, context):
        """Pattern 3 - Server Streaming: one request → many responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Calculate(self, request_iterator, context):
        """Pattern 4 - Bidirectional Streaming: many requests → many responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=calculator__pb2.AddRequest.FromString,
                    response_serializer=calculator__pb2.AddResponse.SerializeToString,
            ),
            'RunningSum': grpc.stream_unary_rpc_method_handler(
                    servicer.RunningSum,
                    request_deserializer=calculator__pb2.NumberRequest.FromString,
                    response_serializer=calculator__pb2.SumResponse.SerializeToString,
            ),
            'MultiplyTable': grpc.unary_stream_rpc_method_handler(
                    servicer.MultiplyTable,
                    request_deserializer=calculator__pb2.MultiplyRequest.FromString,
                    response_serializer=calculator__pb2.MultiplyResponse.SerializeToString,
            ),
            'Calculate': grpc.stream_stream_rpc_method_handler(
                    servicer.Calculate,
                    request_deserializer=calculator__pb2.OperationRequest.FromString,
                    response_serializer=calculator__pb2.OperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Service Definition

    """

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.Calculator/Add',
            calculator__pb2.AddRequest.SerializeToString,
            calculator__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunningSum(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/calculator.Calculator/RunningSum',
            calculator__pb2.NumberRequest.SerializeToString,
            calculator__pb2.SumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MultiplyTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/calculator.Calculator/MultiplyTable',
            calculator__pb2.MultiplyRequest.SerializeToString,
            calculator__pb2.MultiplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Calculate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/calculator.Calculator/Calculate',
            calculator__pb2.OperationRequest.SerializeToString,
            calculator__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
